name: adcolony
description: Ad Network plugin for banners, rewards and interstitial ads show
version: 2.0.7
homepage: https://github.com/DevelopGadget/flutter_adcolony

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.developgadget.adcolony
        pluginClass: AdcolonyPlugin
